### ISSUE TITLE
 I do not know if it's a problem or just my stupidity I'm a complete beginner in these things

### ISSUE THREAD

**Issue by Fpsroxas** [fateloli/MudaeFarm#1]
![image](https://user-images.githubusercontent.com/45643566/52909373-583daa00-3266-11e9-9158-5a61fda4722b.png)
is this that happens.

**Comment by phosphene47** [comment]
make sure you followed all steps

**Comment by Fpsroxas** [comment]
I Did but only to be sure a repeat all steps but it continue to happen

**Comment by phosphene47** [comment]
solved
