### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by cold030** [fateloli/MudaeFarm#2]
All that  happens when i get the program running is that it does marryup to check if you have a claim available but never actually rolls or claims. Is there something seperate I have to do to get this to happen?

**Comment by zubatto** [comment]
happening to me too
![image](https://user-images.githubusercontent.com/48436342/54116688-df271200-4421-11e9-80fa-9cfdba445583.png)

**Comment by phosphene47** [comment]
this is likely solved by recent fixes. reopen this thread if issue persists.
